import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter_chardet/src/native_detector.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('detect performance stays within the unit-test threshold', () {
    const iterations = 200;
    const warmupIterations = 20;
    const maxAverageMicros = 20000;

    final results = <_PerformanceResult>[];
    for (final benchmark in _benchmarks) {
      final bytes = Uint8List.fromList(File(benchmark.path).readAsBytesSync());
      for (var i = 0; i < warmupIterations; i++) {
        NativeDetector.detect(bytes);
      }

      final samples = <int>[];
      for (var i = 0; i < iterations; i++) {
        final stopwatch = Stopwatch()..start();
        final candidate = NativeDetector.detect(bytes);
        stopwatch.stop();
        samples.add(stopwatch.elapsedMicroseconds);
        expect(candidate.charset, isNotEmpty);
      }

      final result = _PerformanceResult(
        name: benchmark.name,
        path: benchmark.path,
        bytes: bytes.length,
        iterations: iterations,
        averageMicros: samples.reduce((a, b) => a + b) / samples.length,
        minMicros: samples.reduce(min),
        maxMicros: samples.reduce(max),
      );
      results.add(result);
      expect(result.averageMicros, lessThan(maxAverageMicros));
    }

    if (Platform.environment['UPDATE_PERFORMANCE_RESULTS'] == '1') {
      _writeResults(results);
    }

    expect(File('docs/performance_results.md').existsSync(), isTrue);
  });
}

const _benchmarks = [
  _Benchmark('UTF-8 English', 'test/upstream/en/utf-8.txt'),
  _Benchmark('Shift_JIS Japanese', 'test/upstream/ja/shift_jis.txt'),
  _Benchmark('Big5 Chinese', 'test/upstream/zh/big5.txt'),
  _Benchmark('Windows-1251 Russian', 'test/upstream/ru/windows-1251.txt'),
];

void _writeResults(List<_PerformanceResult> results) {
  final buffer = StringBuffer()
    ..writeln('# Performance Results')
    ..writeln()
    ..writeln('Generated by:')
    ..writeln()
    ..writeln('```sh')
    ..writeln(
      'UPDATE_PERFORMANCE_RESULTS=1 flutter test test/performance_test.dart',
    )
    ..writeln('```')
    ..writeln()
    ..writeln(
      '- Platform: ${Platform.operatingSystem} ${Platform.operatingSystemVersion}',
    )
    ..writeln('- Dart: ${Platform.version}')
    ..writeln('- Warmup iterations: 20')
    ..writeln()
    ..writeln(
      '| Case | Fixture | Bytes | Iterations | Average us | Min us | Max us |',
    )
    ..writeln('| --- | --- | ---: | ---: | ---: | ---: | ---: |');

  for (final result in results) {
    buffer.writeln(
      '| ${result.name} | `${result.path}` | ${result.bytes} | '
      '${result.iterations} | ${result.averageMicros.toStringAsFixed(2)} | '
      '${result.minMicros} | ${result.maxMicros} |',
    );
  }

  File('docs/performance_results.md').writeAsStringSync(buffer.toString());
}

final class _Benchmark {
  const _Benchmark(this.name, this.path);

  final String name;
  final String path;
}

final class _PerformanceResult {
  const _PerformanceResult({
    required this.name,
    required this.path,
    required this.bytes,
    required this.iterations,
    required this.averageMicros,
    required this.minMicros,
    required this.maxMicros,
  });

  final String name;
  final String path;
  final int bytes;
  final int iterations;
  final double averageMicros;
  final int minMicros;
  final int maxMicros;
}
