import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');

  FfiGenerator(
    output: Output(
      dartFile: packageRoot.resolve(
        'lib/flutter_chardet_bindings_generated.dart',
      ),
      commentType: const CommentType.none(),
      preamble: '''
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `dart run tool/ffigen.dart`.
''',
    ),
    headers: Headers(
      entryPoints: [packageRoot.resolve('src/flutter_chardet.h')],
    ),
    functions: Functions.includeSet({
      'flutter_chardet_new',
      'flutter_chardet_delete',
      'flutter_chardet_active_detectors',
      'flutter_chardet_handle_data',
      'flutter_chardet_data_end',
      'flutter_chardet_reset',
      'flutter_chardet_get_n_candidates',
      'flutter_chardet_get_confidence',
      'flutter_chardet_get_encoding',
      'flutter_chardet_get_language',
    }),
    typedefs: Typedefs.includeSet({'flutter_chardet_t'}),
  ).generate();
}
